version: "3.4"
x-logging: &logging
  logging:
    options:
      max-size: 10m
      max-file: "3"

services:
  taiko_client_prover_relayer:
    image: gcr.io/evmchain/taiko-client:jolnir
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - zkevm_chain_prover_rpcd
    ports:
      - "${PORT_PROVER_SERVER}:9876"
    env_file:
      - .env
    volumes:
      - ./script:/script
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-prover-relayer.sh"
    <<: *logging

  taiko_client_proposer:
    image: gcr.io/evmchain/taiko-client:jolnir
    restart: unless-stopped
    pull_policy: always
    env_file:
      - .env
    volumes:
      - ./script:/script
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-proposer.sh"
    <<: *logging

  zkevm_chain_prover_rpcd:
    image: gcr.io/evmchain/jolnir-proverd:latest
    restart: unless-stopped
    pull_policy: always
    env_file:
      - .env
    volumes:
      - ./script:/script
      - zkevm_chain_prover_rpcd_data:/data
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-zkevm-chain-rpcd.sh"
    deploy:
      replicas: ${ZKEVM_CHAIN_INSTANCES_NUM:-1}
      resources:
        limits:
          memory: 32G
    <<: *logging

volumes:
  zkevm_chain_prover_rpcd_data:
