version: "3.4"
x-logging: &logging
  logging:
    options:
      max-size: 10m
      max-file: "3"

services:
  apus_client:
    image: irongyi/apus-contract-client
    volumes:
      - ./.env:/app/.env
    command: python scripts/contract_lib.py
  zkevm_chain_prover_rpcd:
    image: gcr.io/evmchain/jolnir-proverd:latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - 0.0.0.0:9000:9000
    env_file:
      - .env
    volumes:
      - ./script:/script
      - zkevm_chain_prover_rpcd_data:/data
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-zkevm-chain-rpcd.sh"
    deploy:
      replicas: ${ZKEVM_CHAIN_INSTANCES_NUM:-1}
      resources:
        limits:
          memory: 32G
    depends_on:
      apus_client
    <<: *logging

volumes:
  l2_execution_engine_data:
  zkevm_chain_prover_rpcd_data:
  prometheus_data:
  grafana_data: